disabled_rules: # rule identifiers turned on by default to exclude from running
  - trailing_whitespace
  - multiple_closures_with_trailing_closure
  - identifier_name

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - "*.generated.swift"